#!/bin/bash
echo "Performance Optimization Script"
echo ""
echo "Step 1: Install tools (if needed)"
echo "brew install imagemagick webp"
echo ""
echo "Step 2: Run these commands in your images/ directory:"
echo "cd images"
echo ""
echo "# Optimize logo"
echo "convert logo.png -strip -resize 400x -quality 90 logo-opt.jpg"
echo "cwebp -q 90 logo-opt.jpg -o logo.webp"
echo ""
echo "# Optimize commercial.jpg"
echo "convert commercial.jpg -strip -resize 1200x -quality 82 commercial-opt.jpg"
echo "cwebp -q 80 commercial-opt.jpg -o commercial.webp"
